module(
    name = "cool_raspberries",
    version = "1.0.0",
)

bazel_dep(name = "rules_jvm_external", version = "7.1")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")

maven.install(
    artifacts = [
        "com.fazecast:jSerialComm:2.11.4",
        "com.samskivert:jmustache:1.16",
        "io.javalin:javalin:7.2.3",
        "org.junit.platform:junit-platform-console-standalone:1.12.2",
        "org.bouncycastle:bcpkix-jdk18on:1.85",
        "org.bouncycastle:bcprov-jdk18on:1.85",
        "org.slf4j:slf4j-jdk14:2.0.17",
    ],
    known_contributing_modules = ["protobuf"],
    lock_file = "//:rules_jvm_external++maven+maven_install.json",
    repositories = ["https://repo.maven.apache.org/maven2"],
)

use_repo(maven, "maven")
